### PR TITLE
Changes to recovery so it works in higher dimensions/phase space

### PR DESCRIPTION
**Pull request by manauref**
The changes primarily deal with how a basis is loaded, and we construct the perpendicular basis.

Could the reviewer (e.g. Petr) please confirm or help me confirm that this didn't break anything (in for example the FPO or DiscontPoisson kernels)?

### CODE REVIEW

**Review by pcagas — CHANGES_REQUESTED** [review]
These changes break the code. Here is a simple example of why this doesn't work:
maxima

**Comment by ammarhakim** [comment]
Petr and I have spent endless hours on design of the recovery stuff. I don't want to make any changes without serious discussion. We need to extend to full 6D for sure but let's not be in a rush.

**Comment by ammarhakim** [comment]
I am closing this pull request. We need some more discussion of this on how to do this correctly. Recovery is critical to us and I don't want anything done in a rush. @manauref  Please set up a dev meeting so we can discuss this carefully.

**Comment by manauref** [comment]
Petr and I are talking about this and it won’t be merged until we resolve it. I think it’s just a matter of undoing some of the changes and using the recovery unit test Petr put in.

Because I merged this branch into the diffDirs branch, the changes are there too.

**Pull request closed without merging**
