### PR TITLE
Wrap parts of g0's proj_on_basis and eval_on_nodes

### PR DESCRIPTION
**Pull request by manauref**
(this goes with g0's PR 195 https://github.com/ammarhakim/gkylzero/pull/195)

Wrap parts of g0's proj_on_basis and eval_on_nodes. The intention is twofold:
a) have results in g2 that are closer (to machine precision) to those obtained with g2, and keep both codes in line.
b) phase out Eigen.

This also adds the ability to do Gauss-Lobatto quadrature in ProjectOnBasis.

Add some unit tests.

An interesting discovery in this whole thing:
1. Gauss-lobatto quadrature (GLQ) is in general not the same as EvalOnNodes. These are only the same for the functions in the space span by the basis, e.g. x for p=1, x^2 for p=2.
2. GLQ appears to be more accurate than EvalOnNodes.
3. GLQ does not always enforce continuity at cell boundaries.
It's possible that the latter can be fixed in the limit of infinite number of nodes, but we didn't check that.

### CODE REVIEW

**Comment by ammarhakim** [comment]
I am confused by this PR. Didn't you say we need to change GLQ in G0 before we merge this PR?

**Comment by manauref** [comment]
I wasn't aware that eval_on_nodes was implemented in g0. So no, we don't
HAVE to do anything about GLQ. We just have to be careful about when to use
it (or not use it at all).

**Comment by ammarhakim** [comment]
We need to close this PR so it is not accidentally merged: we first need to resolve PR 195 in G0 and then this PR can be reopened.

**Comment by manauref** [comment]
reverted the last commit in g0. We now need this PR for g2 to work

**Pull request merged**
