### PR TITLE
Discont poisson aux funcs

### PR DESCRIPTION
**Pull request by manauref**
I'd like to merge this branch into master, but @pcagas and @ammarhakim should check it. This branch does two things:
- Plugs in the Spectra library (an Eigen-based library https://github.com/yixuan/spectra). Otherwise evaluating eigenvalues would require us to take the SparseMatrix that Petr is using and put its contents in a dense matrix, then call .eigenvalues(). But that would be inefficient.
- It adds a function to DiscontPoisson to ask for eigenvalues.

To add Spectra to the gkeyll build go into install-depts, run mkdeps.sh again, then you'll have to reconfigure and do ./waf build install again. TO CONFIGURE: 

Add the following line below the line where EIGEN_INC_DIR is declared in configure-par.sh (or whatever configure script you use):

\# SPECTRA options
SPECTRA_INC_DIR=$HOME/gkylsoft/spectra/include/

And you'll have to change the configure command to (this just appends --spectra-inc-dir=$SPECTRA_INC_DIR):
cmd="./waf --out=$OUT --prefix=$PREFIX --cxxflags=$CXXFLAGS --luajit-inc-dir=$LUAJIT_INC_DIR --luajit-lib-dir=$LUAJIT_LIB_DIR --luajit-share-dir=$LUAJIT_SHARE_DIR  $ENABLE_MPI --mpi-inc-dir=$MPI_INC_DIR --mpi-lib-dir=$MPI_LIB_DIR --mpi-link-libs=$MPI_LINK_LIBS $ENABLE_ADIOS --adios-inc-dir=$ADIOS_INC_DIR --adios-lib-dir=$ADIOS_LIB_DIR --eigen-inc-dir=$EIGEN_INC_DIR --spectra-inc-dir=$SPECTRA_INC_DIR configure"

I didn't want to edit the configure file checked in before you guys approve this.

### CODE REVIEW

**Comment by pcagas** [comment]
Shell we add the spectra options to configure-par.sh-in?

**Comment by manauref** [comment]
I didn't want to add it to the configure file checked in until you guys
test/approve this. But yes, Spectra options will need to be added to the
configure files as my pullrequest message describes. I can do this (it'll
have to be added to all the configure files in /machines) once you guys
test/approve.

**Comment by pcagas** [comment]
Oh, I missed the last line, sorry!

**Comment by ammarhakim** [comment]
I am worried about the added dependency. Is this really needed? I want this to be optional and the code should build without the dependency when not needed.

**Comment by ammarhakim** [comment]
Some more work is needed before we can merge this branch.

**Pull request closed without merging**
