### PR TITLE
Axisymmetric & Braginskii terms; external field

### PR DESCRIPTION
**Pull request by liangwang0734**
### Summary of changes
- Support static emf in `AnisotropicDiffusion` and `BraginskiiHeatConduction` updaters.
- In `PlasmaOnCartGrid`, pass `ExternalField` to `FluidSource`.
  - Set `nGhost` to 2 if `numBasis>1` in `ExternalMaxwellField`.
- Use `ExternalField` in `BraginskiiHeatConductionSource`, though presently it is used only by `BraginskiiHeatConductionSource`, not by `CollisionlessEmSource`.
- Fix bugs in `BraginskiiHeatConductionSource` and `BraginskiiViscosityDiffusion`.
- Consolidate `Rregression/mom-braginskii`.
- Add regression test `rt-phmaxwell-circular-waveguide-TE` 
  -  This new `TE` triggers nontrivial phiB update in the axisymmetric source term. In comparison, the `rt-phmaxwell-circular-waveguide-TM` test does not produce any divB from the initial condition.
  - This needs more investigation. Over time `TE` test produces div(B) that looks a little bit funny but the E/B fields look largely ok after 100 periods. Over a long time (>40 periods), the `TM` test fails altogether, possibly due to the axis boundary.
  - __There might be a timing mismatch in the phiB term in the axisymmetric source__. For example, in the `TE` test, there are strange grid-scale structures at the end of the first time step near where div(B) flips sign, after the finite-volume sweep along z. It is possible such mismatching is causing more problems in more complete tests like the dean flow, etc. (One may uses this [divB.py script](https://gist.github.com/liangwang0734/455436c3b1687559fac450e28e43fb9e) to make divB plots from Gkyl field outputs).

### TODOs
- Turn to use `ExternalField` in the basic `CollisionlessEmSource` and `FiveMomentSrc` updaters, etc.

### CODE REVIEW

**Comment by JunoRavin** [comment]
So are you now separating the staticEM specification outside of the source update? How do the Regression tests pass if the source updater now expects a different specification for the static fields?

**Comment by liangwang0734** [comment]
I haven't touched the static EMF in the `CollisionlessEmSource` nor `FiveMomentSrc`. But even if I do that, I don't expect the behavior to change. The staticEm in `CollisionlessEmSource` is just an 8-component field.

**Comment by JunoRavin** [comment]
Oh I see, you have appended another input onto the source update, which is used by Braginskii but not be collisionlessEmSources correct?

**Comment by liangwang0734** [comment]
> Oh I see, you have appended another input onto the source update, which is used by Braginskii but not be collisionlessEmSources correct?

Correct. Also, my plan is to allow `CollisionlessEmSource` to use `ExternalField` as well to avoid duplicate memory allocation. I know you are working on simplifying those codes, though?

**Pull request merged**
