### PR TITLE
Modify time-steppers so that they are written in FSM form and located outside of PlasmaOnCartGrid

### PR DESCRIPTION
**Pull request by manauref**
Here we write the time steppers (RK2, RK3, etc) in the g0 finite state machine (FSM) form. And we also perform the following changes:
1. Place the different time steppers in Apps/TimeSteppers. This cleans up PlasmaOnCartGrid a bit, and now it has basically the same flow for all models. This also required importing files in the middle of PlasmaOnCartGrid (see lines 106-115), which seems a bit odd to me and I would appreciate some feedback on a better way to do it if you think it's wrong.
2. Separate forwardEuler into dydt and forwardEuler. The former just computes the time rates of change, and the latter performs the actual forward step, applies BCs, and sets the time step.

Most of the regression tests will fail because FSM stepping may not follow the exact same sequence of steps as our previous steppers. But I visually checked most of them and they looked fine/reasonable.

I want to do this PR before PRing the super-time-stepping stuff, which has some additional changes that should be reviewed separately.

### CODE REVIEW

**Comment by manauref** [comment]
Some timings. I ran each test 5 times on my laptop, with the master at 4680ad8e and the fsmStep at 96827906. I also plotted dt for each:

vm-weibel/rt-weibel-1x2v-p2 average wall clock time:
- master: (3.3598+3.7881+7.3253+7.7631+7.4710)/5 = 5.9415 s
- fsmStep: (3.8346+4.1096+4.1385+3.9952+3.9147)/5 = 3.9985 s
Screen Shot 2021-08-03 at 4 22 09 PM

vm-weibel/rt-weibel-2x2v-p2 average wall clock time:
- master: (4.0094+3.8977+3.6602+3.7253+3.9783)/5 = 3.8542 s
- fsmStep: (3.9377+3.7623+3.9316+3.9588+3.9741)/5 = 3.9129 s
Screen Shot 2021-08-03 at 4 20 56 PM

gk-sheath/rt-gk-sheath-3x2v-p1 average wall clock time:
- master: (14.7741+14.1878+14.1366+13.8736+14.4152)/5 =  14.2775 s
- fsmStep: (21.3685+23.1942+21.9740+21.8711+22.8955)/5 = 22.2607 s
master used a dt that was 60% larger:
Screen Shot 2021-08-03 at 4 23 21 PM


gk-solovev/rt-gk-sheath-solovev average wall clock time:
- master: (13.6127+13.1581+13.1372+12.1459+12.6799)/5 =  12.9468 s
- fsmStep: (12.8466+13.8626+13.6353+13.7332+12.4846)/5 = 13.3125 s
Screen Shot 2021-08-03 at 4 24 35 PM

**Comment by nmandell** [comment]
Why is the fsm dt smaller in most cases? For GK sheath 60% is a lot, what is going on there?

**Comment by ammarhakim** [comment]
Yes this is not right. Just changing the way stepping works should not reduce dt by so much.

**Comment by manauref** [comment]
I believe I followed the exact same logic as in g0, so I would venture a guess saying that the same thing is happening there.
@ammarhakim @JunoRavin can we run the 2x2v p2 Weibel test in g0 and plot dt to see if it gives the same plot as above?

**Comment by ammarhakim** [comment]
The dt in G0 is same as in G2. Typically the code runs 3-4x faster in fact.

**Comment by ammarhakim** [comment]
I looked at the timings. With the same inputs the G0 dt is 0.111072 and in G2 is 0.1110338. So essentially the same.

**Comment by ammarhakim** [comment]
Actually, I think the 4D Weibel problems in G0 and G2 are different (I mean different parameters). However, the two-stream tests are identical and dt are essentially the same. Before we merge this we need to understand why FSM takes smaller time-steps. We should not merge unless this issue is fully understood.

**Comment by nmandell** [comment]
I’m mostly concerned about the 60% dt drop in gk-sheath. That would not be good if it holds for full nonlinear runs. Also why is dt constant for fsm instead of dynamically changing?

**Comment by ammarhakim** [comment]
Yes, I agree that a 60% increase in dt is something to be concerned about.
Clearly we do not want this to happen in nonlinear simulations! It would be
a disaster.

The fact that dt is not changing could indicate that the suggested dt is
not being set correctly or used.

**Comment by ammarhakim** [comment]
My suggestion is that Mana try and understand why the sheath problem is so different and also run a nonlinear problem to see what happens. We should meet perhaps Friday to go over the logic so we understand what is going on. Till then I think this PR should not be accepted.

**Comment by manauref** [comment]
In response to two issues raised:
1) What does this mean for nonlinear simulations? I have run nonlinear 3x2v GK p1 ES and EM with the FSM on Cori, as part of my tests of STS. I haven't run them until the system is fully turbulent but I can, and I can show you that data.
2) Why is dt smaller? I brought this up as a concern in the weeks prior to the g0 hackathon because it seemed to me that the g0 logic doesn't allow dt to increase after it's dropped. One quick solution to this is, in g2 for example, change line 469 of PlasmaOnCartGrid from
```local dtMin = dt```
to
```local dtMin = GKYL_MAX_DOUBLE```
If you do that the time trace of the gk-sheath-3x2v-p1 test is the following:
Screen Shot 2021-08-03 at 6 52 37 PM
and the timing becomes (14.6627+15.4013+17.7441+16.7684+17.6316)/5 = 16.4416 s, which closer but is still 15% slower than master. I would guess this is small differences in dt + inefficiencies in the FSM implementation (which could be improved, and I invite others to read through the code).

**Comment by nmandell** [comment]
Aha. #2 seems like a g0 bug. The timestep should be able to increase if it wants to and can do so stably.

**Comment by ammarhakim** [comment]
It’s possible.  Jimmy and I thought we had taken care of the increasing dt. But who knows.

**Comment by ammarhakim** [comment]
I looked at G0 code and fixed a tiny error that was not allowing the FSM to suggest a larger time-step. The issue was that I choose the initial suggested dt to the input one. If I choose DBL_MAX this problem goes away. 

The key point is that the time-stepper should not take a dt **larger than told by the user**. However, the stepper should return the suggested time-step which is larger and the user can either use that or ignore it. 

Also, 15% slow-down is significant. As such we should not do this. If every "improvement" we make slows the code down by 15% we will be pretty much going to snail's pace in no-time. One of the goals of the G0 layer is to avoid overheads and be performance oriented. 

In fact, one of the improvements I would like to make in our testing is to isolate a few tests for timing and we then track these as function of time. We already do this in our present system, BTW. Each run-time is recorded in the sqlite DB. I have noticed a slow creep of inefficiencies and perhaps @pcagas can make plots for some of the test from his accumulated DB of information from regression tests. However, I hope by the time 2022 rolls around and G0 is merged into G2, we will not allow branch merges that slow down the code without good reason.

**Comment by manauref** [comment]
So I believe some of the slowdown comes from the way g0 is choosing the time step/checking the CFL in each stage.

For example, if I set dt_maxRelDiff=0.9 so that no stage failures occur (but also a slightly higher dt is allowed) then the timings are (13.3849+13.8864+14.06245+15.3236+13.74198)/5 = 14.08 which is about 2% faster than master.

**Comment by ammarhakim** [comment]
There is some inconsistency and ambiguity on what to do if a dt fails in later stages. Clearly, there will be some impact on performance if the step fails due to later RK-stage failure as the previous stages need to be redone. However, in G0 itself this is not an issue. When the speed up is 2x or so these things do not matter.

What I suggest is that in G2 for now to choose the relDiff such that later stage failures are rare or do not occur. We can revisit this issue later.

**Pull request merged**
